#--- Postgres ---
dataSource.driverClassName=org.postgresql.Driver
jpa.database=POSTGRESQL
dataSource.url=jdbc:postgresql://localhost:5432/vehicle_shop
dataSource.username=postgres
dataSource.password=Zuruha96
spring.jpa.hibernate.ddl-auto=update

# ActiveMQ Artemis configuration
spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

# JMS configuration
spring.jms.pub-sub-domain=false
spring.jms.listener.auto-startup=true
spring.jms.listener.acknowledge-mode=auto

# ????????? pool (???????????)
spring.artemis.pool.enabled=false